version: "3"
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - user-service
      - faq-service

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"

  user-service:
    build:
      context: ./user-service
    ports:
      - "8083:8083"

  faq-service:
    build:
      context: ./faq-service
    ports:
      - "8084:8084"
